routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['namespace' => 'Client'], function(){
	Route::get('/', 'PagesController@index')->name('welcome');
	Route::get('/services/packages', 'PagesController@packages')->name('client.packages');
	Route::get('/services/packages/{id}/{slug}', 'PagesController@packageIndividual')->name('client.packages.individual');
	Route::get('/services/hotels', 'PagesController@hotels')->name('client.hotels');
	Route::get('/services/hotels/{id}/{slug}', 'PagesController@hotelIndividual')->name('client.hotels.individual');
	Route::get('/services/vehicles', 'PagesController@vehicles')->name('client.vehicles');
	Route::get('/services/vehicles/{id}/{slug}', 'PagesController@vehicleIndividual')->name('client.vehicles.individual');

	Route::get('/about', 'PagesController@about')->name('client.about');
	Route::get('/contact', 'PagesController@contact')->name('client.contact');
	Route::get('/account', 'PagesController@account')->name('client.account');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function(){
	Route::get('/', 'DashboardController@admin')->name('admin.index');
	Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
	Route::resource('/roles', 'RoleController');
	Route::resource('/users', 'UserController');
	
	Route::resource('/settings/hotels/facilities', 'HotelFacilityController');
	Route::resource('/settings/hotels/hoteltypes', 'HotelTypeController');
	Route::resource('/settings/hotels/roomtypes', 'HotelRoomTypeController');
	Route::resource('/settings/places/countries', 'CountryController');
	Route::resource('/settings/places/provinces', 'ProvinceController');
	Route::resource('/settings/places/cities', 'CityController');
	Route::resource('/settings/vehicles/vfeatures', 'VehicleFeatureController');
	Route::resource('/settings/packages/pfeatures', 'PackageFeatureController');
	Route::resource('/settings/system/admin', 'SystemAdminController');
	Route::resource('/settings/system/client', 'SystemClientController');

	Route::resource('/services/hotels', 'HotelController');
	Route::resource('/services/hotels/{id}/rooms', 'HotelRoomController');
	Route::resource('/services/hotels/{id}/hgalleries', 'HotelGalleryController');
	Route::resource('/services/hotels/{id}/roomrates', 'HotelRoomRateController');
	Route::resource('/services/hotels/{id}/hvideos', 'HotelVideoController');
	Route::resource('/services/vehicles', 'VehicleController');
	Route::resource('/services/vehicles/{id}/vgalleries', 'VehicleGalleryController');
	Route::resource('/services/vehicles/{id}/vrates', 'VehicleRateController');
	Route::resource('/services/vehicles/{id}/vvideos', 'VehicleVideoController');
	Route::resource('/services/packages', 'PackageController');
	Route::resource('/services/packages/{id}/prates', 'PackageRateController');
	Route::resource('/services/packages/{id}/pgalleries', 'PackageGalleryController');
	Route::resource('/services/packages/{id}/pitineraries', 'PackageItineraryController');
	Route::resource('/services/packages/{id}/pguides', 'PackageGuideController');
	Route::resource('/services/packages/{id}/pvideos', 'PackageVideoController');

	Route::get('/services/hotels/{id}/hgalleries/{hgallery}/rooms','HotelGalleryController@roomIndex')
		->name('hgalleries.roomIndex');
	Route::get('/services/hotels/{id}/hgalleries/{hgallery}/rooms/create','HotelGalleryController@roomCreate')
		->name('hgalleries.roomCreate');
	Route::post('/services/hotels/{id}/hgalleries/{hgallery}/rooms/create','HotelGalleryController@roomStore')
		->name('hgalleries.roomStore');

	Route::resource('/booking/bookings', 'BookingController');
	Route::resource('/booking/requests', 'BookingRequestController');
	Route::resource('/booking/suggests', 'BookingSuggestController');
	Route::resource('/pages/contacts', 'ContactController');
	Route::resource('/pages/abouts', 'AboutController');
	Route::resource('/pages/blog/posts', 'PostController');
	Route::resource('/pages/home/background', 'HomeBackgroundController');
	Route::resource('/pages/home/increadibleplaces', 'HomeIncreadibleplaceController');
	Route::resource('/pages/home/partners', 'HomePartnerController');
	Route::resource('/pages/home/popular', 'HomePopularController');
	Route::resource('/pages/home/topdestinations', 'HomeTopdestinationController');
	Route::resource('/pages/home/videos', 'HomeVideoController');
	

	/***  AJAX ROUTE ***/
	Route::group(['prefix' => 'api', 'namespace' => 'Ajax'], function(){
		Route::get('hotels','AppAjaxController@hotels')->name('hotels.api');
		Route::get('rooms','AppAjaxController@rooms')->name('rooms.api');
		Route::get('hotel/rooms','AppAjaxController@hotelRooms')->name('hotelRooms.api');
		Route::get('vehicles','AppAjaxController@vehicles')->name('vehicles.api');
		Route::get('users','AppAjaxController@users')->name('users.api');
		Route::get('packages','AppAjaxController@packages')->name('packages.api');
		Route::get('getpermissions','AppAjaxController@getrole')->name('getrole.api');
		Route::get('hotel-locations','AppAjaxController@hotelLocations')->name('hotelLocations.api');
		Route::get('countries','AppAjaxController@countries')->name('countries.api');
		Route::get('provinces','AppAjaxController@provinces')->name('provinces.api');
		Route::get('cities','AppAjaxController@cities')->name('cities.api');
		Route::get('topdestination/update','AppAjaxController@topdestinationUpdate')->name('topdestinationUpdate.api');
		Route::get('increadibleplace/update','AppAjaxController@increadibleplaceUpdate')->name('increadibleplaceUpdate.api');
	});
});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => 'index']);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
}

resources/views/admin/pages/home/increadibleplaces/_form-modal.blade.php
<div class="form-group row">
    <label class="col-md-4 col-form-label text-right" for="name">Name :</label>
    <div class="col-md-8">
        <input class="form-control form {{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" type="text" placeholder="Name" required name="name" value="{{ isset($detail) ? $detail->name : old('name') }}">
        @if ($errors->has('name'))
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label class="col-md-4 col-form-label text-right" for="location">Location :</label>
    <div class="col-md-8">
        <select data-placeholder="Location"  class="form-control select-location {{ $errors->has('location') ? ' is-invalid' : '' }}" name="location" required="">
            @if(isset($detail))
                <option value="{{$detail->country_id}}|{{$detail->province_id}}|{{$detail->city_id}}">
                    {{ ($detail->city->name) ? $detail->city->name.', ' : '' }}
                    {{ ($detail->province->name) ? $detail->province->name.', ' : '' }}
                    {{ $detail->country->name }}
                </option>
            @endif
        </select>
        @if ($errors->has('location'))
            <span class="help-block">
                <strong>{{ $errors->first('location') }}</strong>
            </span>
        @endif
    </div>
</div>
@if(isset($detail))
    <input type="hidden" name="detail_id" value="{{ $detail->id }}">
@endif
@include('partials.single-photo')

@push('append_js')
<script type="text/javascript">
    $(document).ready(function(){
        $(".select-location").select2({
            minimumInputLength : 1,
            allowClear: false,
            ajax : {
                url : "{{ route('hotelLocations.api') }}",
                dataType : 'json',
                data : function (params) {
                    return {
                        name: params.term
                    };
                },
                processResults: function (data) {
                      return {
                        results: data
                    };
                },
                cache: true
            }
            ,
            escapeMarkup: function (markup) { return markup; },
            templateResult: function(repo) {
                return repo.text;
            },
            templateSelection: function(repo){
                return repo.text;
            }
        });
    });
</script>
@endpush

resources/views/admin/pages/home/increadibleplaces/_form.blade.php
{{ csrf_field() }}
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="title">Title :</label>
    <div class="col-md-7">
        <input class="form-control form {{ $errors->has('title') ? ' is-invalid' : '' }}" id="title" type="text" placeholder="Title" required name="title" value="{{ isset($increadibleplace) ? $increadibleplace->title : old('title') }}">
        @if ($errors->has('title'))
            <span class="help-block">
                <strong>{{ $errors->first('title') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="description">Description :</label>
    <div class="col-md-7">
        <textarea rows="4" placeholder="Description" class="form-control form {{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" id="description" required>{{ isset($increadibleplace) ? $increadibleplace->description : old('description') }}</textarea>
        @if ($errors->has('description'))
            <span class="help-block">
                <strong>{{ $errors->first('description') }}</strong>
            </span>
        @endif
    </div>
</div>
@include('partials.status', ['data' => (isset($increadibleplace) ? $increadibleplace : null)])

resources/views/admin/pages/home/increadibleplaces/edit.blade.php
@extends('admin.layouts.master')

@section('title', 'Home - Increadible Places')

@section('header-title')
   <i class="list-icon feather feather-globe"></i> Pages
@endsection

@section('header-body')
    <span>Home</span>
    <i class="feather feather-chevron-right"></i>
    <span>Increadible Places</span>
@endsection

@section('content')
    <div class="widget-list">
        <div class="row">
            <div class="widget-holder col-md-12">
                <div class="widget-bg">
                    <div class="widget-heading widget-heading-border">
                        <h5 class="widget-title">Edit</h5>
                        <div class="widget-actions">
                             @include('partials.add-list',['entity' => 'increadibleplaces','reference' => 'Increadible Place'])
                        </div>
                        <!-- /.widget-actions -->
                    </div>
                    <!-- /.widget-heading -->
                    <div class="widget-body">
                        <div class="tabs">
                            @include('admin.pages.home.partials.nav')
                            <!-- /.nav-tabs -->
                            <div class="tab-content">
                                <form class="form-horizontal" data-pjax action="{{route('increadibleplaces.update',$increadibleplace->id)}}" method="POST" autocomplete="off" enctype="multipart/form-data">
                                    {{ method_field('PATCH') }}
                                    @include('admin.pages.home.increadibleplaces._form')
                                    <div class="form-group row">
                                        <label class="col-md-3 col-form-label text-right"></label>
                                        <div class="col-md-5">
                                            @can('edit_increadibleplaces')
                                                <button type="submit" name="save" value="save" class="btn btn-success btn-rounded btn-sm"> Update</button>
                                            @endcan
                                        </div>
                                    </div>
                                </form>
                                @if(count($increadibleplace))
                                    <hr/>
                                    <h6 class="form-section">Location Details</h6>
                                    <button type="button" class="btn btn-info btn-rounded btn-sm pull-right" data-toggle="modal" data-target=".add-image">
                                        <i class="list-icon feather feather-plus"></i>
                                        Image
                                    </button>
                                    <div class="table-responsive">
                                        <table class="table table-striped table-hover" id="data-table">
                                            <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Location</th>
                                                @can('edit_increadibleplaces', 'delete_increadibleplaces')
                                                    <th class="text-center">Actions</th>
                                                @endcan
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($increadibleplace->details as $item)
                                                <tr>
                                                    <td>{{ $item->name }}</td>
                                                    <td class=>
                                                        {{ ($item->city->name) ? $item->city->name.', ' : '' }}
                                                        {{ ($item->province->name) ? $item->province->name.', ' : '' }}
                                                        {{ $item->country->name }}
                                                    </td>
                                                    @can('edit_increadibleplaces','delete_increadibleplaces')
                                                        <td class="text-center">
                                                            <a title="Edit" href="#" class="btn btn-sm btn-rounded btn-info edit-btn"
                                                                data-toggle="modal" data-target=".add-image"
                                                                data-id="{{ $item->id }}"
                                                            >
                                                                <i class="fa fa-pencil"></i>
                                                            </a>
                                                            <form  data-pjax action="{{route('increadibleplaces.destroy', $id)}}" style="display: inline" onsubmit="return confirm('Do you really want to delete it?')" method="POST">
                                                                {{csrf_field()}}
                                                                {{ method_field('DELETE') }}
                                                                <input type="hidden" name="detal_id" value="{{ $item->id }}">
                                                                <button title="Delete" type="submit" class="btn-delete btn btn-sm btn-rounded btn-danger">
                                                                    <i class="fa fa-trash-o"></i>
                                                                </button>
                                                        </form>
                                                        </td>
                                                    @endcan
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                @endif
                            </div>
                            <!-- /.tab-content -->
                        </div>
                    </div>
                    <!-- /.widget-body -->
                </div>
                <!-- /.widget-bg -->
            </div>
            <!-- /.widget-holder -->
        </div>
        <!-- /.row -->
    </div>


    <!-- Modal -->
    <div class="modal fade add-image" role="dialog" aria-labelledby="imageModal" aria-hidden="true" style="display: none">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h5 class="modal-title" id="imageModal">
                        Top Destination Location
                    </h5>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" id="image-add-update" name="image-add-update" data-pjax action="{{route('increadibleplaces.update',$increadibleplace->id)}}" method="POST" autocomplete="off" enctype="multipart/form-data">
                        {{ method_field('PATCH') }}
                        {{ csrf_field() }}
                        <div class="results">
                            @include('admin.pages.home.increadibleplaces._form-modal')
                        </div>
                    </form>
                </div>
                <div class="modal-footer"> 
                    <button type="submit" form="image-add-update" type="submit" class="btn btn-success btn-rounded ripple text-left btn-sm">
                        Submit
                    </button>
                    <button type="button" class="btn btn-default btn-rounded ripple text-left btn-sm" data-dismiss="modal">
                        Close
                    </button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- End modal -->

    @push('append_js')

        <script type="text/javascript">
            
            $(document).ready(function(){
                $('.edit-btn').click(function(e){
                    e.preventDefault();
                    var id = $(this).data('id');
                    var url = "{{ route('increadibleplaceUpdate.api') }}";
                    $.get(url,{id:id},function(results){
                        $('form#image-add-update').find('.results').html(results);
                    });
                });
            });

        </script>

    @endpush
@endsection

resources/views/admin/pages/home/increadibleplaces/index.blade.php
@extends('admin.layouts.master')

@section('title', 'Home - Increadible Places')

@section('header-title')
   <i class="list-icon feather feather-globe"></i> Pages
@endsection

@section('header-body')
    <span>Home</span>
    <i class="feather feather-chevron-right"></i>
    <span>Increadible Places</span>
@endsection

@section('content')
    <div class="widget-list">
        <div class="row">
            <div class="widget-holder col-md-12">
                <div class="widget-bg">
                    <div class="widget-heading widget-heading-border">
                        <h5 class="widget-title">List</h5>
                        <div class="widget-actions">
                             @include('partials.add-list',['entity' => 'increadibleplaces','reference' => 'Increadible Place'])
                        </div>
                        <!-- /.widget-actions -->
                    </div>
                    <!-- /.widget-heading -->
                    <div class="widget-body">
                        <div class="tabs">
                            @include('admin.pages.home.partials.nav')
                            <!-- /.nav-tabs -->
                            <div class="tab-content">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover" id="data-table">
                                        <thead>
                                        <tr>
                                            <th>Description</th>
                                            <th>Status</th>
                                            @can('edit_increadibleplaces', 'delete_increadibleplaces')
                                                <th class="text-center">Actions</th>
                                            @endcan
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($results as $item)
                                            <tr>
                                                <td>{{ $item->description }}</td>
                                                <td>
                                                    @if($item->status == "Draft")
                                                        <span class="badge bg-info ">{{ $item->status }}</span>
                                                    @elseif($item->status == "Published")
                                                        <span class="badge bg-success ">{{ $item->status }}</span>
                                                    @elseif($item->status == "Pending")
                                                        <span class="badge bg-warning ">{{ $item->status }}</span>
                                                    @endif
                                                </td>
                                                @can('edit_increadibleplaces','delete_increadibleplaces')
                                                    <td class="text-center">
                                                       @include('partials.actions', [
                                                            'entity' => 'increadibleplaces',
                                                            'id' => $item->id
                                                        ])
                                                    </td>
                                                @endcan
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                {{ $results->links() }}
                            </div>
                            <!-- /.tab-content -->
                        </div>
                    </div>
                    <!-- /.widget-body -->
                </div>
                <!-- /.widget-bg -->
            </div>
            <!-- /.widget-holder -->
        </div>
        <!-- /.row -->
    </div>
@endsection

resources/views/admin/pages/home/increadibleplaces/new.blade.php
@extends('admin.layouts.master')

@section('title', 'Home - Increadible Places')

@section('header-title')
   <i class="list-icon feather feather-globe"></i> Pages
@endsection

@section('header-body')
    <span>Home</span>
    <i class="feather feather-chevron-right"></i>
    <span>Increadible Places</span>
@endsection

@section('content')
    <div class="widget-list">
        <div class="row">
            <div class="widget-holder col-md-12">
                <div class="widget-bg">
                    <div class="widget-heading widget-heading-border">
                        <h5 class="widget-title">Create</h5>
                        <div class="widget-actions">
                             @include('partials.add-list',['entity' => 'increadibleplaces','reference' => 'Increadible Place'])
                        </div>
                        <!-- /.widget-actions -->
                    </div>
                    <!-- /.widget-heading -->
                    <div class="widget-body">
                        <div class="tabs">
                            @include('admin.pages.home.partials.nav')
                            <!-- /.nav-tabs -->
                            <div class="tab-content">
                                <form class="form-horizontal" data-pjax action="{{route('increadibleplaces.store')}}" method="POST" autocomplete="off" enctype="multipart/form-data">
                                    @include('admin.pages.home.increadibleplaces._form')
                                    <div class="form-group row">
                                        <label class="col-md-3 col-form-label text-right"></label>
                                        <div class="col-md-5">
                                            @can('add_increadibleplaces')
                                                <button type="submit" name="save" value="save" class="btn btn-success btn-rounded btn-sm"> Submit</button>
                                            @endcan
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <!-- /.tab-content -->
                        </div>
                    </div>
                    <!-- /.widget-body -->
                </div>
                <!-- /.widget-bg -->
            </div>
            <!-- /.widget-holder -->
        </div>
        <!-- /.row -->
    </div>
@endsection