routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['namespace' => 'Client'], function(){
	Route::get('/', 'PagesController@index')->name('welcome');
	Route::get('/services/packages', 'PagesController@packages')->name('client.packages');
	Route::get('/services/packages/{id}/{slug}', 'PagesController@packageIndividual')->name('client.packages.individual');
	Route::get('/services/hotels', 'PagesController@hotels')->name('client.hotels');
	Route::get('/services/hotels/{id}/{slug}', 'PagesController@hotelIndividual')->name('client.hotels.individual');
	Route::get('/services/vehicles', 'PagesController@vehicles')->name('client.vehicles');
	Route::get('/services/vehicles/{id}/{slug}', 'PagesController@vehicleIndividual')->name('client.vehicles.individual');

	Route::get('/about', 'PagesController@about')->name('client.about');
	Route::get('/contact', 'PagesController@contact')->name('client.contact');
	Route::get('/account', 'PagesController@account')->name('client.account');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function(){
	Route::get('/', 'DashboardController@admin')->name('admin.index');
	Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
	Route::resource('/roles', 'RoleController');
	Route::resource('/users', 'UserController');
	
	Route::resource('/settings/hotels/facilities', 'HotelFacilityController');
	Route::resource('/settings/hotels/hoteltypes', 'HotelTypeController');
	Route::resource('/settings/hotels/roomtypes', 'HotelRoomTypeController');
	Route::resource('/settings/places/countries', 'CountryController');
	Route::resource('/settings/places/provinces', 'ProvinceController');
	Route::resource('/settings/places/cities', 'CityController');
	Route::resource('/settings/vehicles/vfeatures', 'VehicleFeatureController');
	Route::resource('/settings/packages/pfeatures', 'PackageFeatureController');
	Route::resource('/settings/system/admin', 'SystemAdminController');
	Route::resource('/settings/system/client', 'SystemClientController');

	Route::resource('/services/hotels', 'HotelController');
	Route::resource('/services/hotels/{id}/rooms', 'HotelRoomController');
	Route::resource('/services/hotels/{id}/hgalleries', 'HotelGalleryController');
	Route::resource('/services/hotels/{id}/roomrates', 'HotelRoomRateController');
	Route::resource('/services/hotels/{id}/hvideos', 'HotelVideoController');
	Route::resource('/services/vehicles', 'VehicleController');
	Route::resource('/services/vehicles/{id}/vgalleries', 'VehicleGalleryController');
	Route::resource('/services/vehicles/{id}/vrates', 'VehicleRateController');
	Route::resource('/services/vehicles/{id}/vvideos', 'VehicleVideoController');
	Route::resource('/services/packages', 'PackageController');
	Route::resource('/services/packages/{id}/prates', 'PackageRateController');
	Route::resource('/services/packages/{id}/pgalleries', 'PackageGalleryController');
	Route::resource('/services/packages/{id}/pitineraries', 'PackageItineraryController');
	Route::resource('/services/packages/{id}/pguides', 'PackageGuideController');
	Route::resource('/services/packages/{id}/pvideos', 'PackageVideoController');

	Route::get('/services/hotels/{id}/hgalleries/{hgallery}/rooms','HotelGalleryController@roomIndex')
		->name('hgalleries.roomIndex');
	Route::get('/services/hotels/{id}/hgalleries/{hgallery}/rooms/create','HotelGalleryController@roomCreate')
		->name('hgalleries.roomCreate');
	Route::post('/services/hotels/{id}/hgalleries/{hgallery}/rooms/create','HotelGalleryController@roomStore')
		->name('hgalleries.roomStore');

	Route::resource('/booking/bookings', 'BookingController');
	Route::resource('/booking/requests', 'BookingRequestController');
	Route::resource('/booking/suggests', 'BookingSuggestController');
	Route::resource('/pages/contacts', 'ContactController');
	Route::resource('/pages/abouts', 'AboutController');
	Route::resource('/pages/blog/posts', 'PostController');
	Route::resource('/pages/home/background', 'HomeBackgroundController');
	Route::resource('/pages/home/increadibleplaces', 'HomeIncreadibleplaceController');
	Route::resource('/pages/home/partners', 'HomePartnerController');
	Route::resource('/pages/home/popular', 'HomePopularController');
	Route::resource('/pages/home/topdestinations', 'HomeTopdestinationController');
	Route::resource('/pages/home/videos', 'HomeVideoController');
	

	/***  AJAX ROUTE ***/
	Route::group(['prefix' => 'api', 'namespace' => 'Ajax'], function(){
		Route::get('hotels','AppAjaxController@hotels')->name('hotels.api');
		Route::get('rooms','AppAjaxController@rooms')->name('rooms.api');
		Route::get('hotel/rooms','AppAjaxController@hotelRooms')->name('hotelRooms.api');
		Route::get('vehicles','AppAjaxController@vehicles')->name('vehicles.api');
		Route::get('users','AppAjaxController@users')->name('users.api');
		Route::get('packages','AppAjaxController@packages')->name('packages.api');
		Route::get('getpermissions','AppAjaxController@getrole')->name('getrole.api');
		Route::get('hotel-locations','AppAjaxController@hotelLocations')->name('hotelLocations.api');
		Route::get('countries','AppAjaxController@countries')->name('countries.api');
		Route::get('provinces','AppAjaxController@provinces')->name('provinces.api');
		Route::get('cities','AppAjaxController@cities')->name('cities.api');
		Route::get('topdestination/update','AppAjaxController@topdestinationUpdate')->name('topdestinationUpdate.api');
		Route::get('increadibleplace/update','AppAjaxController@increadibleplaceUpdate')->name('increadibleplaceUpdate.api');
	});
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
class Post extends Model
{
    protected $guarded = ['id'];

    protected $fillable = [
        'title', 'body', 'author_id', 'slug', 'status'
    ];

    public static function findBySlug($slug){
    	return static::where('slug',$slug)->firstOrFail();
    }

    public static function setSlug($text){
    	$text = str_slug($text,'-');
    	
    	$count = static::where('slug','like','%'.$text.'%')->count();
    	return ($count > 0) ? $text . '-' . ($count + 1) : $text;
    }

    public function author(){
        return $this->belongsTo(User::class,'author_id');
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Photo;
use App\Post;
use App\Authorizable;
class PostController extends Controller
{
    use Authorizable;

    public function __construct(){
        $this->page_num = 10;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $results = Post::orderBy('updated_at','desc')->paginate($this->page_num);
        return view('admin.pages.blog.posts.index', compact('results'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.blog.posts.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|min:1',
            'body' => 'required|min:15',
            'author_id' => 'required|min:1',
            'status' => 'required|min:1'
        ]);

        $fill = $request->all();
        $fill['slug'] = Post::setSlug($request->input('title'));

        if ( $post = Post::create($fill)) {

            if($request->hasFile('images')){
                Photo::upload($request->file('images'),'posts',$post->id);
            }

            $request->session()->flash('toast-alert-success', 'Post successfully created.');

        } else {
            $request->session()->flash('toast-alert-danger', 'Unable to create post.');
        }

        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $photos = Photo::where('ref_id',$post->id)
                ->where('model_type','posts')
                ->get();
        return view('admin.pages.blog.posts.edit', compact('post','photos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required|min:1',
            'body' => 'required|min:15',
            'author_id' => 'required|min:1',
            'status' => 'required|min:1'
        ]);

        $post = Post::findOrFail($id);

        $fill = $request->all();
        $fill['slug'] = Post::setSlug($request->input('title'));

        $post->fill($fill);

        $post->save();
        
        if($request->hasFile('images')){
            Photo::upload($request->file('images'),'posts',$post->id);
        }

        if(count($request->input('removephotoid')) && count($request->input('removephotoname'))){
            Photo::removeFile($request->input('removephotoid'));
        }
        $request->session()->flash('toast-alert-success', 'Post successfully updated.');

        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $post = Post::findOrFail($id);

        if( $post->delete() ) {
            Photo::removeByReference($id,'posts');
            $request->session()->flash('toast-alert-success', 'Post successfully deleted.');
        } else {
            $request->session()->flash('toast-alert-warning', 'Post not deleted.');
        }

        return redirect()->back();
    }
}

resources/views/admin/pages/blog/posts/_form.blade.php
{{ csrf_field() }}
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="author_id">Author :</label>
    <div class="col-md-7">
        <select id="author_id" data-placeholder="Author" class="form-control {{ $errors->has('author_id') ? ' is-invalid' : '' }}" name="author_id">
            @if(isset($post))
                <option value="{{ $post->author_id }}" >{{ $post->author->firstname }} {{ $post->author->lastname }}</option>
            @elseif($errors->has('author_id'))
                <option value="{{ old('author_id') }}" >{{ App\User::getName(old('author_id')) }}</option>
            @else
                <option value="{{ auth()->user()->id }}" >{{ auth()->user()->firstname }} {{  auth()->user()->lastname }}</option>
            @endif
        </select>
        @if ($errors->has('author_id'))
            <span class="help-block">
                <strong>{{ $errors->first('author_id') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="title">Title :</label>
    <div class="col-md-7">
        <input class="form-control form {{ $errors->has('title') ? ' is-invalid' : '' }}" id="title" placeholder="" type="text" placeholder="Title" required name="title" value="{{ isset($post) ? $post->title : old('title') }}">
        @if ($errors->has('title'))
            <span class="help-block">
                <strong>{{ $errors->first('title') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="body">Body :</label>
    <div class="col-md-7">
        <textarea data-toggle="tinymce" rows="6" class="form-control form {{ $errors->has('body') ? ' is-invalid' : '' }}" name="body" id="body" required>{{ isset($post) ? $post->body : old('body') }}</textarea>
        @if ($errors->has('body'))
            <span class="help-block">
                <strong>{{ $errors->first('body') }}</strong>
            </span>
        @endif
    </div>
</div>
@include('partials.status', ['data' => (isset($post) ? $post : null)])
<h6 class="form-section">Upload Images</h6>
@include('partials.photo')
@push('append_js')
    <script src="{{ asset('plugins/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ asset('plugins/tinymce/themes/inlite/theme.min.js') }}"></script>
    <script src="{{ asset('plugins/tinymce/jquery.tinymce.min.js') }}"></script>

    <script type="text/javascript">
        $("select#author_id").select2({
            minimumInputLength : 1,
            allowClear: false,
            ajax : {
                url : "{{ route('users.api') }}",
                dataType : 'json',
                data : function (params) {
                    return {
                        name: params.term
                    };
                },
                processResults: function (data) {
                      return {
                        results: data
                    };
                },
                cache: true
            }
            ,
            escapeMarkup: function (markup) { return markup; },
            templateResult: function(repo) {
                return repo.text;
            },
            templateSelection: function(repo){
                return repo.text;
            }
        });
    </script>
@endpush

resources/views/admin/pages/blog/posts/edit.blade.php
@extends('admin.layouts.master')

@section('title', 'Blog - Post')

@section('header-title')
   <i class="list-icon feather feather-globe"></i> Pages
@endsection

@section('header-body')
    <span>Blog</span>
    <i class="feather feather-chevron-right"></i>
    <span>Posts</span>
@endsection

@section('content')
<div class="widget-list">
    <div class="row">
        <div class="widget-holder col-md-12">
            <div class="widget-bg">
                <div class="widget-heading widget-heading-border">
                    <h5 class="widget-title">Edit</h5>
                    <div class="widget-actions">
                        @include('partials.add-list',['entity' => 'posts','reference' => 'Posts'])
                    </div>
                    <!-- /.widget-actions -->
                </div>
                <!-- /.widget-heading -->
                <div class="widget-body">
                    <form class="form-horizontal" data-pjax action="{{route('posts.update',$post->id)}}" method="POST" autocomplete="off" enctype="multipart/form-data">
                        {{ method_field('PATCH') }}
                        @include('admin.pages.blog.posts._form')
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label text-right"></label>
                            <div class="col-md-5">
                                @can('add_posts')
                                    <button type="submit" name="update" value="update" class="btn btn-success btn-rounded btn-sm"> Update</button>
                                @endcan
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.widget-body -->
            </div>
            <!-- /.widget-bg -->
        </div>
        <!-- /.widget-holder -->
    </div>
    <!-- /.row -->
</div>
@endsection

resources/views/admin/pages/blog/posts/index.blade.php
@extends('admin.layouts.master')

@section('title', 'Blog - Post')

@section('header-title')
   <i class="list-icon feather feather-globe"></i> Pages
@endsection

@section('header-body')
    <span>Blog</span>
    <i class="feather feather-chevron-right"></i>
    <span>Posts</span>
@endsection

@section('content')
    <div class="widget-list">
        <div class="row">
            <div class="widget-holder col-md-12">
                <div class="widget-bg">
                    <div class="widget-heading widget-heading-border">
                        <h5 class="widget-title">List</h5>
                        <div class="widget-actions">
                            @include('partials.add-list',['entity' => 'posts','reference' => 'Posts'])
                        </div>
                        <!-- /.widget-actions -->
                    </div>
                    <!-- /.widget-heading -->
                    <div class="widget-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover" id="data-table">
                                <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Body</th>
                                    <th>Author</th>
                                    <th>Status</th>
                                    @can('edit_posts', 'delete_posts')
                                    <th class="text-center">Actions</th>
                                    @endcan
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($results as $item)
                                    <tr>
                                        <td>{{ $item->title }}</td>
                                        <td>{!! str_limit($item->body,40) !!}</td>
                                        <td>{{ $item->author->lastname.' '.$item->author->firstname }}</td>
                                        <td>
                                            @if($item->status == "Draft")
                                                <span class="badge bg-info ">{{ $item->status }}</span>
                                            @elseif($item->status == "Published")
                                                <span class="badge bg-success ">{{ $item->status }}</span>
                                            @elseif($item->status == "Pending")
                                                <span class="badge bg-warning ">{{ $item->status }}</span>
                                            @endif
                                        </td>
                                        @can('edit_posts')
                                        <td class="text-center">
                                           @include('partials.actions', [
                                                'entity' => 'posts',
                                                'id' => $item->id
                                            ])
                                        </td>
                                        @endcan
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        {{ $results->links() }}
                    </div>
                    <!-- /.widget-body -->
                </div>
                <!-- /.widget-bg -->
            </div>
            <!-- /.widget-holder -->
        </div>
        <!-- /.row -->
    </div>
@endsection

resources/views/admin/pages/blog/posts/new.blade.php
@extends('admin.layouts.master')

@section('title', 'Blog - Post')

@section('header-title')
   <i class="list-icon feather feather-globe"></i> Pages
@endsection

@section('header-body')
    <span>Blog</span>
    <i class="feather feather-chevron-right"></i>
    <span>Posts</span>
@endsection

@section('content')
<div class="widget-list">
    <div class="row">
        <div class="widget-holder col-md-12">
            <div class="widget-bg">
                <div class="widget-heading widget-heading-border">
                    <h5 class="widget-title">Create</h5>
                    <div class="widget-actions">
                        @include('partials.add-list',['entity' => 'posts','reference' => 'Posts'])
                    </div>
                    <!-- /.widget-actions -->
                </div>
                <!-- /.widget-heading -->
                <div class="widget-body">
                    <form class="form-horizontal" data-pjax action="{{route('posts.store')}}" method="POST" autocomplete="off" enctype="multipart/form-data">
                        @include('admin.pages.blog.posts._form')
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label text-right" ></label>
                            <div class="col-md-5">
                                @can('add_posts')
                                    <button type="submit" name="save" value="save" class="btn btn-success btn-rounded btn-sm"> Submit</button>
                                @endcan
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.widget-body -->
            </div>
            <!-- /.widget-bg -->
        </div>
        <!-- /.widget-holder -->
    </div>
    <!-- /.row -->
</div>
@endsection