routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['namespace' => 'Client'], function(){
	Route::get('/', 'PagesController@index')->name('welcome');
	Route::get('/services/packages', 'PagesController@packages')->name('client.packages');
	Route::get('/services/packages/{id}/{slug}', 'PagesController@packageIndividual')->name('client.packages.individual');
	Route::get('/services/hotels', 'PagesController@hotels')->name('client.hotels');
	Route::get('/services/hotels/{id}/{slug}', 'PagesController@hotelIndividual')->name('client.hotels.individual');
	Route::get('/services/vehicles', 'PagesController@vehicles')->name('client.vehicles');
	Route::get('/services/vehicles/{id}/{slug}', 'PagesController@vehicleIndividual')->name('client.vehicles.individual');

	Route::get('/about', 'PagesController@about')->name('client.about');
	Route::get('/contact', 'PagesController@contact')->name('client.contact');
	Route::get('/account', 'PagesController@account')->name('client.account');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function(){
	Route::get('/', 'DashboardController@admin')->name('admin.index');
	Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
	Route::resource('/roles', 'RoleController');
	Route::resource('/users', 'UserController');
	
	Route::resource('/settings/hotels/facilities', 'HotelFacilityController');
	Route::resource('/settings/hotels/hoteltypes', 'HotelTypeController');
	Route::resource('/settings/hotels/roomtypes', 'HotelRoomTypeController');
	Route::resource('/settings/places/countries', 'CountryController');
	Route::resource('/settings/places/provinces', 'ProvinceController');
	Route::resource('/settings/places/cities', 'CityController');
	Route::resource('/settings/vehicles/vfeatures', 'VehicleFeatureController');
	Route::resource('/settings/packages/pfeatures', 'PackageFeatureController');
	Route::resource('/settings/system/admin', 'SystemAdminController');
	Route::resource('/settings/system/client', 'SystemClientController');

	Route::resource('/services/hotels', 'HotelController');
	Route::resource('/services/hotels/{id}/rooms', 'HotelRoomController');
	Route::resource('/services/hotels/{id}/hgalleries', 'HotelGalleryController');
	Route::resource('/services/hotels/{id}/roomrates', 'HotelRoomRateController');
	Route::resource('/services/hotels/{id}/hvideos', 'HotelVideoController');
	Route::resource('/services/vehicles', 'VehicleController');
	Route::resource('/services/vehicles/{id}/vgalleries', 'VehicleGalleryController');
	Route::resource('/services/vehicles/{id}/vrates', 'VehicleRateController');
	Route::resource('/services/vehicles/{id}/vvideos', 'VehicleVideoController');
	Route::resource('/services/packages', 'PackageController');
	Route::resource('/services/packages/{id}/prates', 'PackageRateController');
	Route::resource('/services/packages/{id}/pgalleries', 'PackageGalleryController');
	Route::resource('/services/packages/{id}/pitineraries', 'PackageItineraryController');
	Route::resource('/services/packages/{id}/pguides', 'PackageGuideController');
	Route::resource('/services/packages/{id}/pvideos', 'PackageVideoController');

	Route::get('/services/hotels/{id}/hgalleries/{hgallery}/rooms','HotelGalleryController@roomIndex')
		->name('hgalleries.roomIndex');
	Route::get('/services/hotels/{id}/hgalleries/{hgallery}/rooms/create','HotelGalleryController@roomCreate')
		->name('hgalleries.roomCreate');
	Route::post('/services/hotels/{id}/hgalleries/{hgallery}/rooms/create','HotelGalleryController@roomStore')
		->name('hgalleries.roomStore');

	Route::resource('/booking/bookings', 'BookingController');
	Route::resource('/booking/requests', 'BookingRequestController');
	Route::resource('/booking/suggests', 'BookingSuggestController');
	Route::resource('/pages/contacts', 'ContactController');
	Route::resource('/pages/abouts', 'AboutController');
	Route::resource('/pages/blog/posts', 'PostController');
	Route::resource('/pages/home/background', 'HomeBackgroundController');
	Route::resource('/pages/home/increadibleplaces', 'HomeIncreadibleplaceController');
	Route::resource('/pages/home/partners', 'HomePartnerController');
	Route::resource('/pages/home/popular', 'HomePopularController');
	Route::resource('/pages/home/topdestinations', 'HomeTopdestinationController');
	Route::resource('/pages/home/videos', 'HomeVideoController');
	

	/***  AJAX ROUTE ***/
	Route::group(['prefix' => 'api', 'namespace' => 'Ajax'], function(){
		Route::get('hotels','AppAjaxController@hotels')->name('hotels.api');
		Route::get('rooms','AppAjaxController@rooms')->name('rooms.api');
		Route::get('hotel/rooms','AppAjaxController@hotelRooms')->name('hotelRooms.api');
		Route::get('vehicles','AppAjaxController@vehicles')->name('vehicles.api');
		Route::get('users','AppAjaxController@users')->name('users.api');
		Route::get('packages','AppAjaxController@packages')->name('packages.api');
		Route::get('getpermissions','AppAjaxController@getrole')->name('getrole.api');
		Route::get('hotel-locations','AppAjaxController@hotelLocations')->name('hotelLocations.api');
		Route::get('countries','AppAjaxController@countries')->name('countries.api');
		Route::get('provinces','AppAjaxController@provinces')->name('provinces.api');
		Route::get('cities','AppAjaxController@cities')->name('cities.api');
		Route::get('topdestination/update','AppAjaxController@topdestinationUpdate')->name('topdestinationUpdate.api');
		Route::get('increadibleplace/update','AppAjaxController@increadibleplaceUpdate')->name('increadibleplaceUpdate.api');
	});
});

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $guarded = ['id'];

    protected $fillable = [
        'code', 'name', 'dial_code', 'currency_name', 'currency_symbol', 'currency_code'
    ];

    public function hotels(){
    	return $this->hasMany(Hotel::class,'country_id');
    }
}

app/Http/Controllers/Admin/CountryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Authorizable;
use App\Country;
class CountryController extends Controller
{
    use Authorizable;
    
    public function __construct(){
        $this->page_num = 10;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $results = Country::latest()->paginate($this->page_num);
        return view('admin.settings.places.countries.index', compact('results'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.settings.places.countries.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:1',
            'currency_name' => 'required|min:1'

        ]);

        if ( $country = Country::create($request->all()) ) {

            $request->session()->flash('toast-alert-success', 'Country successfully created.');

        } else {
            $request->session()->flash('toast-alert-danger', 'Unable to create country.');
        }

        return redirect()->route('countries.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $country = Country::findOrFail($id);

        return view('admin.settings.places.countries.edit', compact('country'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|min:1',
            'currency_name' => 'required|min:1'

        ]);

        $country = Country::findOrFail($id);

        $country->fill($request->all());

        if($country->isDirty()){
            $country->save();
            $request->session()->flash('toast-alert-success', 'Country successfully updated.');
        }
        else{
            $request->session()->flash('toast-alert-info', 'Nothing to update.');
        }

        return redirect()->route('countries.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $country = Country::findOrFail($id);
        if($country->hotels->count()){
            $request->session()->flash('toast-alert-danger', 'Country already in used.');
            return redirect()->back();
        }
        if( $country->delete() ) {
            $request->session()->flash('toast-alert-success', 'Country successfully deleted.');
        } else {
            $request->session()->flash('toast-alert-warning', 'Country not deleted.');
        }

        return redirect()->back();
    }
}

resources/views/admin/settings/places/countries/_form.blade.php
{{ csrf_field() }}
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="code">Code :</label>
    <div class="col-md-7">
        <input class="form-control form {{ $errors->has('code') ? ' is-invalid' : '' }}" id="code" type="text" placeholder="Code" name="code" value="{{ isset($country) ? $country->code : old('code') }}">
        @if ($errors->has('code'))
            <span class="help-block">
                <strong>{{ $errors->first('code') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="name">Name :</label>
    <div class="col-md-7">
        <input class="form-control form {{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" type="text" placeholder="Name" name="name" value="{{ isset($country) ? $country->name : old('name') }}">
        @if ($errors->has('name'))
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="currency_name">Currency Name :</label>
    <div class="col-md-7">
        <input class="form-control form {{ $errors->has('currency_name') ? ' is-invalid' : '' }}" id="currency_name" placeholder="Currency name" type="text"  name="currency_name" value="{{ isset($country) ? $country->currency_name : old('currency_name') }}">
        @if ($errors->has('currency_name'))
            <span class="help-block">
                <strong>{{ $errors->first('currency_name') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="dial_code">Dial Code :</label>
    <div class="col-md-7">
        <input class="form-control form {{ $errors->has('dial_code') ? ' is-invalid' : '' }}" id="dial_code" placeholder="Dial code" type="text"  name="dial_code" value="{{ isset($country) ? $country->dial_code : old('dial_code') }}">
        @if ($errors->has('dial_code'))
            <span class="help-block">
                <strong>{{ $errors->first('dial_code') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="currency_symbol">Currency Symbol :</label>
    <div class="col-md-7">
        <input class="form-control form {{ $errors->has('currency_symbol') ? ' is-invalid' : '' }}" id="currency_symbol" placeholder="Currency Symbol" type="text" name="currency_symbol" value="{{ isset($country) ? $country->currency_symbol : old('currency_symbol') }}">
        @if ($errors->has('currency_symbol'))
            <span class="help-block">
                <strong>{{ $errors->first('currency_symbol') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label class="col-md-3 col-form-label text-right" for="currency_code">Currency Code :</label>
    <div class="col-md-7">
        <input class="form-control form {{ $errors->has('currency_code') ? ' is-invalid' : '' }}" id="currency_code" placeholder="Currency Code" type="text" name="currency_code" value="{{ isset($country) ? $country->currency_code : old('currency_code') }}">
        @if ($errors->has('currency_code'))
            <span class="help-block">
                <strong>{{ $errors->first('currency_code') }}</strong>
            </span>
        @endif
    </div>
</div>

resources/views/admin/settings/places/countries/edit.blade.php
@extends('admin.layouts.master')

@section('title', 'Countries')

@section('header-title')
   <i class="list-icon feather feather-settings"></i> Settings
@endsection

@section('header-body')
    <span>Places</span>
    <i class="feather feather-chevron-right"></i>
    <span>Countries</span>
@endsection

@section('content')
<div class="widget-list">
    <div class="row">
        <div class="widget-holder col-md-12">
            <div class="widget-bg">
                <div class="widget-heading widget-heading-border">
                    <h5 class="widget-title">Edit</h5>
                    <div class="widget-actions">
                        @include('partials.add-list',['entity' => 'countries','reference' => 'Country'])
                    </div>
                    <!-- /.widget-actions -->
                </div>
                <!-- /.widget-heading -->
                <div class="widget-body">
                    <div class="tabs">
                        @include('admin.settings.places.partials.nav')
                        <!-- /.nav-tabs -->
                        <div class="tab-content">
                            <form class="form-horizontal" action="{{route('countries.update',$country->id)}}" method="POST" autocomplete="off">
                                {{ method_field('PATCH') }}
                                @include('admin.settings.places.countries._form')
                                <div class="form-group row">
                                    <label class="col-md-3 col-form-label text-right"></label>
                                    <div class="col-md-5">
                                        @can('add_countries')
                                            <button type="submit" name="update" value="update" class="btn btn-success btn-rounded btn-sm"> Update</button>
                                        @endcan
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.widget-body -->
            </div>
            <!-- /.widget-bg -->
        </div>
        <!-- /.widget-holder -->
    </div>
    <!-- /.row -->
</div>
@endsection

resources/views/admin/settings/places/countries/index.blade.php
@extends('admin.layouts.master')

@section('title', 'Countries')

@section('header-title')
   <i class="list-icon feather feather-settings"></i> Settings
@endsection

@section('header-body')
    <span>Places</span>
    <i class="feather feather-chevron-right"></i>
    <span>Countries</span>
@endsection

@section('content')
    <div class="widget-list">
        <div class="row">
            <div class="widget-holder col-md-12">
                <div class="widget-bg">
                    <div class="widget-heading widget-heading-border">
                        <h5 class="widget-title">List</h5>
                        <div class="widget-actions">
                            @include('partials.add-list',['entity' => 'countries','reference' => 'Country'])
                        </div>
                        <!-- /.widget-actions -->
                    </div>
                    <!-- /.widget-heading -->
                    <div class="widget-body">
                        <div class="tabs">
                            @include('admin.settings.places.partials.nav')
                            <!-- /.nav-tabs -->
                            <div class="tab-content">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover" id="data-table">
                                        <thead>
                                        <tr>
                                            <th>Code</th>
                                            <th>Name</th>
                                            <th>Currency Name</th>
                                            <th>Currency Code</th>
                                            @can('edit_countries', 'delete_countries')
                                            <th class="text-center">Actions</th>
                                            @endcan
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($results as $item)
                                            <tr>
                                                <td>{{ $item->code }}</td>
                                                <td>{{ $item->name }}</td>
                                                <td>{{ $item->currency_name }}</td>
                                                <td>{{ $item->currency_code }}</td>

                                                @can('edit_countries','delete_countries')
                                                <td class="text-center">
                                                   @include('partials.actions', [
                                                        'entity' => 'countries',
                                                        'id' => $item->id
                                                    ])
                                                </td>
                                                @endcan
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                {{ $results->links() }}
                            </div>
                        </div>
                    </div>
                    <!-- /.widget-body -->
                </div>
                <!-- /.widget-bg -->
            </div>
            <!-- /.widget-holder -->
        </div>
        <!-- /.row -->
    </div>
@endsection

resources/views/admin/settings/places/countries/new.blade.php
@extends('admin.layouts.master')

@section('title', 'Countries')

@section('header-title')
   <i class="list-icon feather feather-settings"></i> Settings
@endsection

@section('header-body')
    <span>Places</span>
    <i class="feather feather-chevron-right"></i>
    <span>Countries</span>
@endsection

@section('content')
<div class="widget-list">
    <div class="row">
        <div class="widget-holder col-md-12">
            <div class="widget-bg">
                <div class="widget-heading widget-heading-border">
                    <h5 class="widget-title">Create</h5>
                    <div class="widget-actions">
                        @include('partials.add-list',['entity' => 'countries','reference' => 'Country'])
                    </div>
                    <!-- /.widget-actions -->
                </div>
                <!-- /.widget-heading -->
                <div class="widget-body">
                    <div class="tabs">
                        @include('admin.settings.places.partials.nav')
                        <!-- /.nav-tabs -->
                        <div class="tab-content">
                            <form class="form-horizontal" action="{{route('countries.store')}}" method="POST" autocomplete="off">
                                @include('admin.settings.places.countries._form')
                                <div class="form-group row">
                                    <label class="col-md-3 col-form-label text-right"></label>
                                    <div class="col-md-5">
                                        @can('add_countries')
                                            <button type="submit" name="save" value="save" class="btn btn-success btn-rounded btn-sm"> Submit</button>
                                        @endcan
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.widget-body -->
            </div>
            <!-- /.widget-bg -->
        </div>
        <!-- /.widget-holder -->
    </div>
    <!-- /.row -->
</div>
@endsection